### ISSUE TITLE
Metrics not working for POJOs/Entities

### ISSUE THREAD

**Issue by kiview** [ryantenney/metrics-spring#111]
It seems like the Annotations don't work for Classes, which aren't managed by Spring (like POJOs, or JPA Entities). Is this intended?

**Comment by ryantenney** [comment]
Correct, in order to instrument an object it must be a spring managed object.  Spring can do autowiring in non-managed beans by enabling Compile Time Weaving (CTW), but I don't think that Spring AOP is compatible with CTW (not positive about this).  A better option may be to use [metrics-aspectj](https://github.com/astefanutti/metrics-aspectj) with AspectJ CTW, but again, I'm not 100% confident that they are compatible.
